{"nick":"Fishrock123","date":"2016-08-31T00:31:07.150Z","type":"join"}
{"nick":"Fishrock123","reason":"Remote host closed the connection","date":"2016-08-31T01:27:47.410Z","type":"quit"}
{"nick":"Fishrock123","date":"2016-08-31T01:42:32.486Z","type":"join"}
{"nick":"Fishrock123","reason":"Remote host closed the connection","date":"2016-08-31T02:25:30.011Z","type":"quit"}
{"nick":"Trott","message":"rvagg jbergstroem:  test-nodesource_ceejbot-debian7-arm_pi1p-1 now blowing up. https://ci.nodejs.org/job/node-test-binary-arm/3576/RUN_SUBSET=addons,label=pi1-raspbian-wheezy/  https://ci.nodejs.org/job/node-test-binary-arm/3576/RUN_SUBSET=0,label=pi1-raspbian-wheezy/ https://ci.nodejs.org/job/node-test-binary-arm/3575/RUN_SUBSET=0,label=pi1-raspbian-wheezy/","date":"2016-08-31T02:44:49.627Z","type":"message"}
{"nick":"Trott","message":"etc.","date":"2016-08-31T02:44:49.705Z","type":"message"}
{"nick":"jbergstroem","message":"Trott: yeah me/rod is aware; tryna figure it out","date":"2016-08-31T02:45:07.766Z","type":"message"}
{"nick":"jbergstroem","message":"nfs issues","date":"2016-08-31T02:45:21.096Z","type":"message"}
{"nick":"Trott","message":"Ah, OK. I thought that was a new one. I thought earlier it was test-nodesource_ceejbot-debian7-arm_pi1p-1","date":"2016-08-31T02:45:39.606Z","type":"message"}
{"nick":"Trott","message":"Oh, wait, yeah, that is the same one. Uh, never mind. :-(","date":"2016-08-31T02:45:49.993Z","type":"message"}
{"nick":"Fishrock123","date":"2016-08-31T03:09:31.535Z","type":"join"}
{"nick":"rvagg","message":"Trott: thanks, it was taken offline ~30 minutes after those failures, still working on it https://ci.nodejs.org/computer/test-nodesource_ceejbot-debian7-arm_pi1p-1/","date":"2016-08-31T03:24:41.484Z","type":"message"}
{"nick":"node-gh","date":"2016-08-31T03:54:36.000Z","type":"join"}
{"nick":"node-gh","date":"2016-08-31T03:54:36.079Z","type":"part"}
{"nick":"node-gh","date":"2016-08-31T03:55:11.000Z","type":"join"}
{"nick":"node-gh","date":"2016-08-31T03:55:11.079Z","type":"part"}
{"nick":"node-gh","date":"2016-08-31T03:59:09.380Z","type":"join"}
{"nick":"node-gh","date":"2016-08-31T03:59:09.458Z","type":"part"}
{"nick":"Fishrock123","reason":"Quit: Leaving...","date":"2016-08-31T04:01:10.876Z","type":"quit"}
{"nick":"jenkins-monitor","reason":"Remote host closed the connection","date":"2016-08-31T05:42:49.214Z","type":"quit"}
{"nick":"jenkins-monitor","date":"2016-08-31T05:43:00.374Z","type":"join"}
{"nick":"rvagg","message":"I've reconnected nfs on test-nodesource_ceejbot-debian7-arm_pi1p-1 and it _looks_ OK so it's back in the cluster, we'll see","date":"2016-08-31T05:53:45.868Z","type":"message"}
{"nick":"node-gh","date":"2016-08-31T06:00:52.044Z","type":"join"}
{"nick":"node-gh","date":"2016-08-31T06:00:52.123Z","type":"part"}
{"nick":"phillipj","message":"gah github squash fail ^","date":"2016-08-31T06:03:29.480Z","type":"message"}
{"nick":"phillipj","message":"ended up as two commits, even tho I used the squash button","date":"2016-08-31T06:03:42.680Z","type":"message"}
{"nick":"phillipj","message":"might be cause I gpg signed my commits lately and those commits cannot be squashed from the github ui","date":"2016-08-31T06:04:53.396Z","type":"message"}
{"nick":"ljharb","message":"wait really? github won't squash gpg-signed commits?","date":"2016-08-31T06:05:14.951Z","type":"message"}
{"nick":"ljharb","message":"so if i gpg-sign my commits nobody can screw them up by squashing them? :-D","date":"2016-08-31T06:05:32.620Z","type":"message"}
{"nick":"starefossen","message":"makes sense if think about it","date":"2016-08-31T06:05:45.320Z","type":"message"}
{"nick":"starefossen","message":"but should be communicated to the user","date":"2016-08-31T06:06:06.063Z","type":"message"}
{"nick":"starefossen","message":"well, they can (if they do it manually) but then the resulting commit will no longer be signed by you","date":"2016-08-31T06:06:55.674Z","type":"message"}
{"nick":"starefossen","message":"s/signed/gpg-signed/","date":"2016-08-31T06:07:26.696Z","type":"message"}
{"nick":"ljharb","message":"sure, but i'm not worried about people doing the wrong thing on the CLI","date":"2016-08-31T06:07:47.718Z","type":"message"}
{"nick":"ljharb","message":"but the github UI makes it really easy to destroy valuable commit granularity","date":"2016-08-31T06:08:01.916Z","type":"message"}
{"nick":"starefossen","message":"true","date":"2016-08-31T06:09:08.908Z","type":"message"}
{"nick":"phillipj","message":"yeah would have been nice to get a warning about what was going to happen","date":"2016-08-31T06:27:27.355Z","type":"message"}
{"nick":"phillipj","message":"cant seem to find those two commits in the git log either","date":"2016-08-31T06:28:14.170Z","type":"message"}
{"nick":"phillipj","message":"thought I'd rebase/push one of those commits away, but my interactive rebase doesn't list the commit gh created :/","date":"2016-08-31T06:29:07.476Z","type":"message"}
{"nick":"node-gh","date":"2016-08-31T06:53:29.749Z","type":"join"}
{"nick":"node-gh","date":"2016-08-31T06:53:29.827Z","type":"part"}
