{"nick":"Coren","message":"bnoordhuis: Well, that /was/ my question.  I'm not seeing a method in the v8::PropertyCallbackInfo for that","date":"2014-11-24T00:37:53.729Z","type":"message"}
{"nick":"plutoniix","reason":"Quit: จรลี จรลา","date":"2014-11-24T01:03:10.098Z","type":"quit"}
{"nick":"jmar777","date":"2014-11-24T01:11:06.074Z","type":"join"}
{"nick":"Coren","message":"bnoordhuis: And I'm in a callback, so just throwing a C++ exception seems... unwise.","date":"2014-11-24T01:14:44.032Z","type":"message"}
{"nick":"jmar777","reason":"Ping timeout: 264 seconds","date":"2014-11-24T01:15:39.328Z","type":"quit"}
{"nick":"seventh","reason":"Remote host closed the connection","date":"2014-11-24T01:16:37.148Z","type":"quit"}
{"nick":"abraxas__","date":"2014-11-24T02:21:52.539Z","type":"join"}
{"nick":"abraxas__","reason":"Ping timeout: 240 seconds","date":"2014-11-24T02:26:17.114Z","type":"quit"}
{"nick":"bnoordhuis","reason":"Ping timeout: 258 seconds","date":"2014-11-24T02:49:17.423Z","type":"quit"}
{"nick":"plutoniix","date":"2014-11-24T02:50:04.368Z","type":"join"}
{"nick":"bnoordhuis","date":"2014-11-24T03:55:40.441Z","type":"join"}
{"nick":"bnoordhuis","reason":"Ping timeout: 250 seconds","date":"2014-11-24T04:00:12.298Z","type":"quit"}
{"nick":"plutoniix","reason":"Ping timeout: 264 seconds","date":"2014-11-24T04:21:29.894Z","type":"quit"}
{"nick":"plutoniix","date":"2014-11-24T04:34:06.594Z","type":"join"}
{"nick":"octetcloud","date":"2014-11-24T06:14:18.695Z","type":"join"}
{"nick":"octetcloud","reason":"Ping timeout: 244 seconds","date":"2014-11-24T06:18:39.077Z","type":"quit"}
{"nick":"abraxas_","date":"2014-11-24T07:48:42.312Z","type":"join"}
{"nick":"rendar","date":"2014-11-24T07:48:54.088Z","type":"join"}
{"nick":"abraxas_","reason":"Ping timeout: 240 seconds","date":"2014-11-24T07:52:52.955Z","type":"quit"}
