{"nick":"BridgeAR","date":"2018-01-14T00:52:08.722Z","type":"join"}
{"nick":"AtumT","reason":"Remote host closed the connection","date":"2018-01-14T01:05:44.153Z","type":"quit"}
{"nick":"doodadjs_","date":"2018-01-14T01:31:06.875Z","type":"join"}
{"nick":"doodadjs","reason":"Ping timeout: 276 seconds","date":"2018-01-14T01:34:53.883Z","type":"quit"}
{"nick":"nodejs-gh","date":"2018-01-14T02:31:52.897Z","type":"join"}
{"nick":"nodejs-gh","date":"2018-01-14T02:31:52.897Z","type":"part"}
{"nick":"BridgeAR","reason":"Quit: Leaving.","date":"2018-01-14T02:39:15.308Z","type":"quit"}
{"nick":"ljharb","message":"a WeakValueMap or a WeakRef would be needed for that; and i think there's tons of complications for it","date":"2018-01-14T02:44:28.246Z","type":"message"}
{"nick":"devsnek","message":"yea its just wishful thinking :(","date":"2018-01-14T02:46:26.831Z","type":"message"}
{"nick":"nodejs-gh","date":"2018-01-14T03:14:28.744Z","type":"join"}
{"nick":"nodejs-gh","date":"2018-01-14T03:14:28.851Z","type":"part"}
{"nick":"nodejs-gh","date":"2018-01-14T04:09:31.735Z","type":"join"}
{"nick":"nodejs-gh","date":"2018-01-14T04:09:31.843Z","type":"part"}
{"nick":"Fusl","reason":"\"WeeChat 2.1-dev\"","date":"2018-01-14T04:11:16.546Z","type":"part"}
{"nick":"nodejs-gh","date":"2018-01-14T05:42:03.577Z","type":"join"}
{"nick":"nodejs-gh","date":"2018-01-14T05:42:03.657Z","type":"part"}
{"nick":"nodejs-gh","date":"2018-01-14T05:54:46.186Z","type":"join"}
{"nick":"nodejs-gh","date":"2018-01-14T05:54:46.254Z","type":"part"}
{"nick":"lpin","date":"2018-01-14T06:40:23.203Z","type":"join"}
{"nick":"TimothyGu","message":"devsnek: I've pushed almost all of the code changes I wanted to make. (Wanted to see if I could factor out the rejects() function in the tests to a test/common.) Force-pushed to your branch","date":"2018-01-14T07:41:23.662Z","type":"message"}
{"nick":"TimothyGu","message":"diff from your original branch for convenience: https://gist.github.com/de3512ca106144be55391a1f5b723286","date":"2018-01-14T07:41:33.508Z","type":"message"}
{"nick":"TimothyGu","message":"re import(): I made all vm.Modules in the main context follow the standard import() algorithm, because there's a 1:1 relationship between Realm and module map. For other contexts, I've currently not done anything to change the status quo (throwing an exception). We can always fix that later","date":"2018-01-14T07:43:46.028Z","type":"message"}
{"nick":"TimothyGu","message":"but the way I want to address it is by adding a new method vm.registerDynamicImportHandlerForContext(contextifiedSandbox, (specifier, referrer) => vm.Module)","date":"2018-01-14T07:44:27.772Z","type":"message"}
{"nick":"TimothyGu","message":"a bug I fixed was m.link(() => { m.instantiate(); }), which was throwing a weird error about \"linking error, not in local cache\"","date":"2018-01-14T07:46:46.985Z","type":"message"}
{"nick":"TimothyGu","message":"now it's throwing a proper MODULE_NOT_LINKED error","date":"2018-01-14T07:47:05.609Z","type":"message"}
{"nick":"TimothyGu","message":"so the two things remaining are (1) rejects() refactor, and (2) documentation updates, which I haven't got the chance to do at all","date":"2018-01-14T07:48:58.847Z","type":"message"}
{"nick":"TimothyGu","message":"I'll do it tomorrow if I get a chance","date":"2018-01-14T07:49:15.759Z","type":"message"}
